### ISSUE TITLE
Include url or text to read later

### ISSUE THREAD

**Issue by SirXOPHER** [andretorres-codurance/restful-reader#9]
- [x] Create endpoint to add new items in back-end
- [x] Add method to repository to add new items to database
- [x] Create front-end to add new items.

**Comment by andretorres-codurance** [comment]
To get the Id in PostgresSQL you need 

```
select nextval('web_id_seq');
```

**Comment by SirXOPHER** [comment]
TODO: Fix error in JSON parsing 
```
ERROR spark.http.matching.GeneralError - 
com.eclipsesource.json.ParseException: Expected digit at 1:2
```
